Worked on the Ui intergartion of reawrds page
Snowball-Finance/axial-frontend pull request #110
Opened 2022-03-14 08:22 UTC by Sanjeev1308

Changed the rewards containers logic because not able to find data
Worked on the data display, read the data from logic components and displayed with proper format

2022-03-18 09:46 UTC, mohsenParvar approved these changes

2022-03-22 16:53 UTC, saito-sv approved these changes
LGTM, please address some minor comments.

2022-03-22 16:53 UTC, saito-sv commented on src/app/pages/Rewards/components/CurrencyReserve/CurrencyInfo.tsx
> +// const IconImage = styled("img")({
remove unused code.

2022-03-22 16:53 UTC, saito-sv commented on src/app/pages/Rewards/selectors.ts
> +              percent: "24.19%",
lets not hardcode values, instead consider using a common file for static values.

2022-03-22 18:52 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-rewards-integration.dev-app.axial.exchange

2022-03-22 21:35 UTC, bigwampa requested changes
Compound w/ Snowball button should link to the appropriate pool on the compound & earn section of snowball.
<img width="473" alt="Screen Shot 2022-03-22 at 2 31 13 PM" src="https://user-images.githubusercontent.com/79389347/159579683-b3aa6cc7-3329-4e2e-b325-0ba385f98245.png">

Approval Checkbox should be visible.
<img width="240" alt="Screen Shot 2022-03-22 at 2 33 49 PM" src="https://user-images.githubusercontent.com/79389347/159579926-b26fbb90-eb19-4607-a51f-dcb41e8a7e4d.png">

There is no slippage when depositing single assets into a rewards pool, please remove.
<img width="541" alt="Screen Shot 2022-03-22 at 2 34 27 PM" src="https://user-images.githubusercontent.com/79389347/159580027-b06f24e0-d0e7-4fa9-8291-e980a9bda89c.png">

Advanced options should toggle open and closed. They should be closed by default.
<img width="544" alt="Screen Shot 2022-03-22 at 2 34 33 PM" src="https://user-images.githubusercontent.com/79389347/159580096-4df26271-78d7-44bc-a03e-d2c23b9360dd.png">

2022-03-24 13:46 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-rewards-integration.dev-app.axial.exchange

2022-03-24 16:53 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-rewards-integration.dev-app.axial.exchange

2022-03-24 17:34 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-rewards-integration.dev-app.axial.exchange

2022-03-30 19:50 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-rewards-integration.dev-app.axial.exchange

2022-03-30 19:56 UTC, merged