Worked on the liquidty page ui integration
Snowball-Finance/axial-frontend pull request #111
Opened 2022-03-14 19:38 UTC by Sanjeev1308

Displayed the data with read only functionality with proper format

2022-03-18 09:40 UTC, mohsenParvar approved these changes

2022-03-18 09:40 UTC, mohsenParvar commented on src/app/pages/Liquidity/subPages/Deposit/components/CurrencyInput.tsx
> +            Wallet balance:{" "}
this should be translated, we have the example of parameter to translation

2022-03-22 16:58 UTC, saito-sv approved these changes
LGTM

2022-03-22 16:58 UTC, saito-sv commented on src/app/pages/Liquidity/subPages/Withdraw/components/CurrencyInput.tsx
> +                </Grid>
looks like this is still a placeholder?

2022-03-22 16:58 UTC, saito-sv approved these changes
LGTM

2022-03-22 18:02 UTC, Sanjeev1308 commented on src/app/pages/Liquidity/subPages/Withdraw/components/CurrencyInput.tsx
> +                </Grid>
No, it will be the USD balance text in future, will be replaced by dynamic data from API/RPC calls

2022-03-22 18:51 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-22 21:28 UTC, bigwampa requested changes
User should be able to input amounts to deposit even if their wallet is not connected or they do not poses the amount in their wallet.
<img width="596" alt="Screen Shot 2022-03-22 at 2 21 26 PM" src="https://user-images.githubusercontent.com/79389347/159578328-1db3cd9f-8c10-48b9-9094-da5c5b1793c6.png">

User should be able to input into max slippage amount and there should be _only one_ slippage selected at a time.
<img width="444" alt="Screen Shot 2022-03-22 at 2 22 59 PM" src="https://user-images.githubusercontent.com/79389347/159578466-5b3b1585-81df-4e47-9817-9a860ffe7e2e.png">

Metapool should only show two tokens, the LP token and the paired token. In the case of USDC-AM3D metapool, it should show USDC and AM3D. It should _not_ show all underlying tokens in the LP.
<img width="1077" alt="Screen Shot 2022-03-22 at 2 25 02 PM" src="https://user-images.githubusercontent.com/79389347/159578815-d0d3add0-ec82-4488-a62c-2ddcfefc13fb.png">

Metapools should optionally take as input _either_ the LP and the paired token, _or_ the underlying tokens in the LP and the paired token. This is supported in our v1.
<img width="447" alt="Screen Shot 2022-03-22 at 2 27 11 PM" src="https://user-images.githubusercontent.com/79389347/159579011-df550e02-5a6c-4186-a6a9-c5f4e3ecbad7.png">

2022-03-22 22:18 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-22 22:22 UTC, Sanjeev1308 commented
> Metapool should only show two tokens, the LP token and the paired token. In the case of USDC-AM3D metapool, it should show USDC and AM3D. It should _not_ show all underlying tokens in the LP.

Resolved the issue, please check, other than this all will be performed @mohsenParvar , had a discussion with him

2022-03-22 23:37 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-23 00:05 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-23 11:22 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-23 12:17 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-23 12:23 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-23 12:45 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-23 12:48 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-23 17:56 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-23 18:13 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-30 19:59 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-30 20:13 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-liquidity-integration.dev-app.axial.exchange

2022-03-30 20:23 UTC, merged