Worked on the new design changes on swap
Snowball-Finance/axial-frontend pull request #112
Opened 2022-03-15 13:52 UTC by Sanjeev1308

Worked on the slippage
Refactor the code

2022-03-18 09:32 UTC, mohsenParvar approved these changes

2022-03-18 16:33 UTC, saito-sv commented on src/app/constants/index.ts
>  export const BaseUrl = `https://base.snowball.io`;
is this a valid URL?

2022-03-18 16:46 UTC, saito-sv approved these changes
LGTM

2022-03-22 18:01 UTC, Sanjeev1308 commented on src/app/constants/index.ts
>  export const BaseUrl = `https://base.snowball.io`;
Not sure, I haven't added this, may be @mohsenParvar provide comments over it

2022-03-22 18:49 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-swap-new-changes.dev-app.axial.exchange

2022-03-22 21:16 UTC, bigwampa requested changes
Approve checkbox is not visible
<img width="141" alt="Screen Shot 2022-03-22 at 2 11 18 PM" src="https://user-images.githubusercontent.com/79389347/159576974-8fe22f03-dbf6-4b8b-a2a4-bf218e0e5a18.png">


Slippage currently doesn't accept input. It should also deselect whichever slippage was previously selected:
<img width="312" alt="Screen Shot 2022-03-22 at 2 14 50 PM" src="https://user-images.githubusercontent.com/79389347/159577191-1d224124-3928-4dbb-a9ef-a6bac71430ea.png">

Finally, every trade route should show the expected trade amount, regardless of whether the user has a wallet connected. This route TUSD to MIM does not show either way.

<img width="171" alt="Screen Shot 2022-03-22 at 2 11 53 PM" src="https://user-images.githubusercontent.com/79389347/159577346-968d8709-2af5-4e62-86b9-68f116b29704.png">

2022-03-25 08:50 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-swap-new-changes.dev-app.axial.exchange

2022-03-25 18:31 UTC, saito-sv commented
@Sanjeev1308  can you fix the conflicts please.

2022-03-28 08:58 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-swap-new-changes.dev-app.axial.exchange

2022-03-30 20:56 UTC, merged