Worked on the mobile navigation design
Snowball-Finance/axial-frontend pull request #117
Opened 2022-03-22 12:47 UTC by Sanjeev1308

2022-03-22 15:50 UTC, mohsenParvar commented on src/app/Layout/components/Header.tsx
> +  [theme.breakpoints.down("sm")]: {
use [mobile] here
we have the example in the governance page

2022-03-22 15:50 UTC, mohsenParvar commented on src/app/Layout/index.tsx
> +  [theme.breakpoints.down("sm")]: {
also here and everywhere you are using `theme.breakpoints.down("sm")`, use [mobile]

2022-03-22 17:01 UTC, saito-sv approved these changes
LGTM

2022-03-22 18:48 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-mobile-navigation.dev-app.axial.exchange

2022-03-22 19:30 UTC, mohsenParvar approved these changes

2022-03-22 21:01 UTC, bigwampa requested changes
UI is failing to scale to mobile devices. Tried on both Android device and mobile device toolbar on desktop browser. Same display issue for navigatio
<img width="426" alt="Screen Shot 2022-03-22 at 2 00 55 PM" src="https://user-images.githubusercontent.com/79389347/159575196-46198a9a-bf26-47e1-891f-621546318e0e.png">
n

2022-03-22 21:04 UTC, Sanjeev1308 commented
> UI is failing to scale to mobile devices. Tried on both Android device and mobile device toolbar on desktop browser. Same display issue for navigatio <img alt="Screen Shot 2022-03-22 at 2 00 55 PM" width="426" src="https://user-images.githubusercontent.com/79389347/159575196-46198a9a-bf26-47e1-891f-621546318e0e.png"> n

Please check with liquidity and rewards page

2022-03-22 21:12 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-mobile-navigation.dev-app.axial.exchange

2022-03-23 12:48 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-mobile-navigation.dev-app.axial.exchange

2022-03-23 13:01 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-mobile-navigation.dev-app.axial.exchange

2022-03-23 13:14 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-mobile-navigation.dev-app.axial.exchange

2022-03-23 13:40 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-mobile-navigation.dev-app.axial.exchange

2022-03-23 14:32 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-mobile-navigation.dev-app.axial.exchange

2022-03-24 18:51 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-task-sanjeev-mobile-navigation.dev-app.axial.exchange

2022-03-25 18:30 UTC, merged