proper modal for liquidity deposit
Snowball-Finance/axial-frontend pull request #131
Opened 2022-04-05 22:55 UTC by mohsenParvar

* proper approval for deposit in liquidity page (can test with deposit in liquidity)
* added functionality for checking the approval of a list of token
* fixed bug with memoized slippage and infinite approval on reload
* refactored approve modal actions
* removed clicking sound on menu hover

2022-04-05 22:56 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-fix-mohsen-liquidity-deposit.dev-app.axial.exchange

2022-04-06 15:45 UTC, saito-sv requested changes

2022-04-06 15:45 UTC, saito-sv commented on src/app/pages/Liquidity/components/modal/Withdraw/index.tsx
>        if (Object.keys(tokenAmounts).length === 1) {
the `else if` are evaluating different things, please consider maybe group them or separate the logic intro 2 sets of if.

2022-04-06 15:45 UTC, saito-sv commented on src/app/pages/Liquidity/components/modal/Withdraw/index.tsx
> +      } else if (selectedToken === "combo") {
consider holding this magic values `combo` and `mixed` into a `constant`
```suggestion
      } else if (selectedToken === tokenSelection.COMBO) {
```

2022-04-06 16:00 UTC, mohsenParvar commented on src/app/pages/Liquidity/components/modal/Withdraw/index.tsx
>        if (Object.keys(tokenAmounts).length === 1) {
this is valid, because if we don't have only one token, the state will be either mixed or combo

2022-04-06 16:48 UTC, saito-sv commented
@mohsenParvar  please fix conflicts

2022-04-06 21:00 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-fix-mohsen-liquidity-deposit.dev-app.axial.exchange

2022-04-07 15:04 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-fix-mohsen-liquidity-deposit.dev-app.axial.exchange

2022-04-07 15:07 UTC, saito-sv commented on src/app/pages/Liquidity/saga.ts
> +    console.debug(
remove  after debugging is complete

2022-04-07 15:08 UTC, saito-sv approved these changes

2022-04-07 17:29 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-fix-mohsen-liquidity-deposit.dev-app.axial.exchange

2022-04-07 17:35 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-fix-mohsen-liquidity-deposit.dev-app.axial.exchange

2022-04-07 17:45 UTC, saito-sv commented
This PR is automatically being deployed to https://preview-fix-mohsen-liquidity-deposit.dev-app.axial.exchange

2022-04-07 18:00 UTC, Sanjeev1308 approved these changes

2022-04-07 18:01 UTC, merged